### PR TITLE
Ivy support

### PR DESCRIPTION
**Pull request by yuri-apanasik**
Here is minimal changes to support Angular 16 (View Engine support was removed in this version, so Ivy distribution is required).
Please, check the possibility to merge the PR and release new version on NPM.
I am open to add some more adjustments if needed.
Thank you.

### CODE REVIEW

**Comment by yuri-apanasik** [comment]
@muratcorlu using your library with Angular 16 is not possible now because of missing Ivy support

**Comment by muratcorlu** [comment]
Hi @yuri-apanasik! Thanks for the contribution. I'm not able to use Angular a lot for a few years, so I lost track of new features. I would like to provide an update for this library for sure. But with this PR, library will not able to work with the version prior to 16, right? Can we cover a broader range of Angular versions? #65 suggests Angular 13 or newer would be enough, if I don't understand wrong. Maybe @inorganik can comment as well?

**Comment by yuri-apanasik** [comment]
@muratcorlu @inorganik changed to 13+ peer dependency
In addition I've replaced tslint with eslint (first one is no longer supported), removed default e2e project (looks like it was not used anyway), used new build with my application (where we used your library and what we can't update to Angular 16 now) - it was ok.
But sure it is better to double check. Would be so good if you will find time to check if everything is ok and publish new version.

**Review by muratcorlu — APPROVED** [review]
Looks good! 🚀 

Let me merge and release this with a major version. If we notice any problem, we can make patch releases as well. Thanks for your help!

**Comment by yuri-apanasik** [comment]
Thank you for the quick reply! We will use new version in our application ...right now :) So, I'll give you know in case any troubles.

**Pull request merged**
