### PR TITLE
Angular8 support

### LINKED ISSUE #15: Upgrade peer dependencies from Angular 7 to 8
Upgrade peer Angular dependencies to avoid the following warnings:

`ngx-script-loader@1.1.0" has incorrect peer dependency "@angular/common@^6.0.0 || ^7.0.0". ngx-script-loader@1.1.0" has incorrect peer dependency "@angular/core@^6.0.0 || ^7.0.0".`

### PR DESCRIPTION
**Pull request by bartholomej**
Support for **Angular8** (fix #15) and fix this annoying warning:
```bash
> ngx-script-loader@1.1.0" has incorrect peer dependency "@angular/common@^6.0.0 || ^7.0.0".
```

Tested:
✓ Your built-in tests passed succefully
✓ Tested with your demo application in ng7 and ng8
✓ Used with ng8 in production app for more than a month

### CODE REVIEW

**Comment by muratcorlu** [comment]
Hey, thanks for your contribution. Somehow CI is broken now. I'll try to check it.

**Comment by bartholomej** [comment]
Hi, yes it's broken but I believe there is only something wrong in docker image because it fails on `apt install google-chrome-stable`.

**Comment by bartholomej** [comment]
So, what do you think? Any news? ;) @muratcorlu

**Comment by muratcorlu** [comment]
I think I fixed the CI issue. Can you merge latest master and push again?

**Comment by bartholomej** [comment]
Great ;) It works! @muratcorlu

**Comment by muratcorlu** [comment]
Merged and released as v1.2.0 https://www.npmjs.com/package/ngx-script-loader

**Comment by bartholomej** [comment]
🤘

**Pull request merged**
